.PHONY: clean All

All:
	@echo "----------Building project:[ SNHUProject1 - Debug ]----------"
	@cd "SNHUProject1" && "$(MAKE)" -f  "SNHUProject1.mk"
clean:
	@echo "----------Cleaning project:[ SNHUProject1 - Debug ]----------"
	@cd "SNHUProject1" && "$(MAKE)" -f  "SNHUProject1.mk" clean
